# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEzWS7DfwOBUCCleQc8PHHh1-ti8nAY0
"""

! pip install gtts

from gtts import gTTS
import os
text = """Je t'aime, je t'aime
Comme un fou comme un soldat
Comme une star de cinéma
Je t'aime, je t'aime
Comme un loup, comme un roi
Comme un homme que je ne suis pas
Tu vois, je t'aime comme ça

D'accord je t'ai confié tous mes sourires, tous mes secrets
Même ceux, dont seul un frère est le gardien inavoué
Dans cette maison de pierre, Satan nous regardait danser
J'ai tant voulu la guerre de corps qui se faisaient la paix"""
language = "fr"
tts=gTTS(text=text, lang=language,slow=False)
audio_file="audio_fransiya.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text = """Я помню чудное мгновенье:
Передо мной явилась ты,
Как мимолётное виденье,
Как гений чистой красоты.

В томленьях грусти безнадежной,
В тревогах шумной суеты,
Звучал мне долго голос нежный
И снились милые черты.

Шли годы. Бурь порыв мятежный
Рассеял прежние мечты,
И я забыл твой голос нежный,
Твои небесные черты."""
language = "ru"
tts=gTTS(text=text, lang=language,slow=False)
audio_file="audio_rus.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text = """Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date;

Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometime declines,
By chance, or nature's changing course untrimm'd"""
language = "en"
tts=gTTS(text=text, lang=language,slow=False)
audio_file="audio_eng.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text = """床前明月光，
疑是地上霜。
举头望明月，
低头思故乡"""
language = "zh-CN"
tts=gTTS(text=text, lang=language,slow=False)
audio_file="audio_China Mainland.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text = """你好"""
language = "zh-CN"
tts=gTTS(text=text, lang=language,slow=False)
audio_file="audio_China-salom.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text = """¿Qué es poesía?, dices mientras clavas
en mi pupila tu pupila azul.
¿Qué es poesía? ¿Y tú me lo preguntas?
Poesía… eres tú."""
language = "es"
tts=gTTS(text=text, lang=language,slow=False)
audio_file="audio_Spanish (Mexico).mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os
text = """
مرحباً! اسمي سوجيدا، وأنا مهتمة بتعلم اللغات والثقافات المختلفة. أحب القراءة والكتابة، وأحب التعلم عن العالم من حولي.
في وقت فراغي، أستمتع بالسفر واستكشاف أماكن جديدة وتجربة أطعمة متنوعة. الحياة مليئة بالتجارب الجميلة، ومن المهم الاستفادة من كل لحظة.
"""
language = "ar"
tts=gTTS(text=text, lang=language,slow=False)
audio_file="audio_arabic.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)